# Generated by Django 6.0 on 2025-12-07 09:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Кошелек')),
                ('balance', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)], verbose_name='Баланс')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='OTO_key_User', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Транзакция')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата транзакции')),
                ('text', models.TextField(max_length=255, verbose_name='текст')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='F_Key_Wallet_WalletTransactions', to='wallet.wallet', verbose_name='Кошелек транзакции')),
            ],
            options={
                'ordering': ['transaction'],
            },
        ),
    ]
