# Generated by Django 6.0 on 2025-12-07 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_add_wallets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-1)], verbose_name='Баланс'),
        ),
    ]
